### ISSUE TITLE
Tracking issue for wireframes

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#14]
Root tracking issue for TSX wireframes:

Steps
- [x] Homepage: https://github.com/ultrabear/soundclone/pull/12
- [x] Song details page:
- [x] My Playlists page:
- [x] Likes page
- [x] #40
- [x] Artist page: https://github.com/ultrabear/soundclone/pull/30
- [ ] User page
- [x] Profile edit page
- [x] Style login/signup modals
