### ISSUE TITLE
Tracking issue for API routes

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#17]
Steps:
- [x] Songs endpoints (joem): https://github.com/ultrabear/soundclone/pull/20
  - [x] Likes endpoints (alex): https://github.com/ultrabear/soundclone/pull/37
- [x] Playlist endpoints (shunchao): https://github.com/ultrabear/soundclone/pull/28
- [x] Comment endpoints (alex): https://github.com/ultrabear/soundclone/pull/18
- [x] Artist endpoints (joec): https://github.com/ultrabear/soundclone/pull/19
- [x] User endpoints: https://github.com/ultrabear/soundclone/pull/13
