### ISSUE TITLE
Tracking issue for AWS integration

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#39]
Steps:
- [x] https://github.com/ultrabear/soundclone/pull/27
- [x] fix spaces in song titles
- [x] style upload form
- [x] implement actual aws urls in song seeders
- [x] set default thumbnail for song uploads lacking a thumbnail_img
