### ISSUE TITLE
Tracking issue for DB Models

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#6]
This is a tracking issue for creating the sqlalchemy database models

Steps:
- [x] Finish schema: https://github.com/ultrabear/soundclone/pull/2
- [x] Build all models and migrations: https://github.com/ultrabear/soundclone/pull/11
- [x] Add User auth stuff (when we get starter): https://github.com/ultrabear/soundclone/pull/13
