### ISSUE TITLE
CRUD Checklist

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#67]
# Checklist of functionality:
## Songs:
- [x] View all
- [x] upload
- [x] update uploaded song
- [x] delete uploaded song
## Comments
- [x] view all on a song
- [x] add comment to song
- [x] edit comment on song
- [x] remove comment on song
## Likes
- [x] View likes on song
- [x] like a song
- [x] unlike a song
## Playlists
- [x] view all playlists
- [x] add a song to a playlist
- [x] remove a song from a playlist
