### ISSUE TITLE
Tracking issue for Backend Progress

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#7]
Steps:
- [x] Finish API schema: https://github.com/ultrabear/soundclone/pull/5
- [x] Finish database models: https://github.com/ultrabear/soundclone/issues/6
- [x] Implement user authentication in flask (starter code): https://github.com/ultrabear/soundclone/pull/13
- [x] Finish API routes in flask: https://github.com/ultrabear/soundclone/issues/17

Goal: finish by end of this week
