### ISSUE TITLE
Tracking issue for Frontend Progress

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#8]
Tracking issue for frontend progress

Steps:
- [ ] Implement wireframes in TSX: https://github.com/ultrabear/soundclone/issues/14
- [x] Design session store: (1: https://github.com/ultrabear/soundclone/pull/10)
- [x] Copy starter code: https://github.com/ultrabear/soundclone/pull/13
- [x] Design playlists store:
- [x] Design songs store:
- [x] Design users store (alex):
- [x] Design comments store (joem):
- [x] Convert components to new store (joec):
- [ ] Completed CSS:
