### ISSUE TITLE
Touchups checklist

### ISSUE THREAD

**Issue by ultrabear** [ultrabear/soundclone#92]
# Alex
1. [x] NowPlaying > AddToPlaylist > CreateNewPlaylist does not route to EditPlaylistPage, it should for consistentcy
1. [x] Login is slow (LoginFormModal)
1. [x] Play all button on artist songs page is not functional
1. [x] UserView reroute to home if not signed on
1. [x] Play all button on playlist details page is not functional
1. [x] Routing to another page should scroll to top
1. [x] Song details and artists - add black shadow (SongDetailsPage)
1. [x] Edit playlist image upload in form (in playlist editing component, upload image instead of url)

# JoeM
1. [x] Sneak Thievery Theme Not Playing (Song seeds)
       Fix: add proper name in AWS GUI
1. [x] Error handling on log in with email and password - invalid credentials not showing (LoginFormModal)
       Display FlaskError
1. [x] My playlists image duplicated  (on /user/playlists)
1. [x] Hyperlinks are colored blue (should not be colored blue)
1. [x] fix aspect ratio on images on (/user/uploads)
1. [x] Use HTML input type "date" for first_release field (/user/profile)
1. [x] My uploads page (/user/uploads) should be more compact (each song entry)
       Making date be a tooltip over title?
1. [x] Extra login/signup buttons on homepage that are redundant
1. [x] Spacing between edit/close and edit/delete on song comments is too small
1. [x] add padding to layout.tsx (NowPlaying cuts off footer content)
# JoeC
1. [x] Waveform player placeholder (SongDetailsPage)
